Update lokalise-push.yml

diff --git a/.github/workflows/lokalise-push.yml b/.github/workflows/lokalise-push.yml
--- a/.github/workflows/lokalise-push.yml
+++ b/.github/workflows/lokalise-push.yml
@@ -4,7 +4,7 @@ on:
   workflow_dispatch:
   push:
     paths:
-      - en.json  # Trigger when this file is updated
+      - 'en.json'  # Trigger when this file is updated
     branches:
       - main  # Only trigger on changes to the main branch
 
@@ -13,15 +13,16 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      # Checkout the repository
       - name: Checkout repository
         uses: actions/checkout@v3
-        with:
-          fetch-depth: 0  # Fetch full history to ensure all file details are available
 
-      # Push the JSON file to Lokalise
       - name: Push JSON file to Lokalise
         run: |
-          curl -v -X POST "https://api.lokalise.com/api2/projects/8924818166f90cfed9af35.66887635/files/upload" \
-          -H "X-Api-Token: 919873230a09f13d63d67ab49874325072977cf9" \
-          -F "file=@en.json"
+          curl -v -X POST "https://api.lokalise.com/api2/projects/${{ secrets.LOKALISE_PROJECT_ID }}/files/upload" \
+             -H "X-Api-Token: ${{ secrets.LOKALISE_API_TOKEN }}" \
+             -F "file=@en.json"
+          if [[ $? -ne 0 ]]; then
+            echo "Error: Failed to upload en.json to Lokalise!"
+            exit 1
+          fi
+          echo "Successfully uploaded en.json to Lokalise!"
